name: Build & push
on:
  push:
    branches: [ main ]
  pull_request:

env:
  USER: root

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host:
          - abhartach
    steps:
      - uses: actions/checkout@v4
      - uses: wimpysworld/nothing-but-nix@main
      - uses: cachix/install-nix-action@v31
      - name: Cachix
        uses: cachix/cachix-action@v16
        with:
          name: conorhk
          extraPullNames: "nix-community"
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true
      - run: nix build -L --no-link .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel
      - run: nix eval --json ".#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel.outPath" | sed 's/"\(.*\)"/\1/' | cachix push conorhk
