name: build
on:
  check_suite:
    types: [completed]
  push:
jobs:
  check:
    runs-on: [self-hosted, nix, x86_64-linux]
    environment: production
    steps:
      - name: Sync repository
        uses: actions/checkout@v4

      - run: nix --extra-experimental-features pipe-operators flake check .?submodules=1

  build-machines:
    needs: check
    strategy:
      matrix:
        include:
          - machine: abhartach
          - machine: bananach
          # - machine: banshee
          - machine: dullahan
          - machine: puca
          - machine: leprechaun

    runs-on: [self-hosted, nix, x86_64-linux]
    environment: production
    steps:
      - name: Sync repository
        uses: actions/checkout@v4

      - run: nix --extra-experimental-features pipe-operators build -L .?submodules=1#nixosConfigurations.${{ matrix.machine }}.config.system.build.toplevel
