name: Build & push

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and push Config
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            release_suffix: ubuntu
    runs-on: ${{ matrix.os }}
    steps:
      - run: sudo rm -rf /opt&
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30
      - uses: cachix/cachix-action@v15
        with:
          name: conorhk
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: x86_64-linux Build
        if: matrix.os == 'ubuntu-latest'
        run: nix '--extra-experimental-features pipe-operators' build -L .#{nixosConfigurations.abhartach.config.system.build.toplevel}

      - name: Deploy
        run: |
          cachix push conorhk ./result*
