name: build and push
on:
  check_suite:
    types: [completed]
  # workflow_dispatch:
  push:
  # pull_request:
jobs:
  build-machines:
    strategy:
      matrix:
        machine:
          - abhartach
        os:
          - ubuntu-latest
          # - macos-latest
          # - ubuntu-24.04-arm

    runs-on: ${{ matrix.os }}
    steps:
      - name: Cleanup host
        uses: wimpysworld/nothing-but-nix@main

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Sync repository
        uses: actions/checkout@v4

      - uses: cachix/cachix-action@v14
        with:
          name: conorhk
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          useDaemon: false
          installCommand: nix profile install nixpkgs#cachix

      - run: nix build -L .?submodules=1#nixosConfigurations.${{ matrix.machine }}.config.system.build.toplevel
