name: renovate
on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:
jobs:
  renovate:
    runs-on: [self-hosted, nix, x86_64-linux]
    environment: production
    steps:
      - name: Sync repository
        uses: actions/checkout@v4

      - run: nix run nixpkgs#renovate -- --platform=github --token=${{ secrets.GITHUB_TOKEN }} ConorHK/blizzard
        env:
          LOG_LEVEL: info
