name: renovate
on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:
jobs:
  renovate:
    runs-on: [self-hosted, nix, x86_64-linux]
    environment: production
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Sync repository
        uses: actions/checkout@v4

      - run: nix run nixpkgs#renovate -- --platform=github ConorHK/blizzard
        env:
          RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG_LEVEL: info
